// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label2;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Label3;
void ui_event_Roller2( lv_event_t * e);
lv_obj_t *ui_Roller2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label13;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label11;
void ui_event_Label7( lv_event_t * e);
lv_obj_t *ui_Label7;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Panel5;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label22;
void ui_event_Button13( lv_event_t * e);
lv_obj_t *ui_Button13;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Button8;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Label26;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t *ui_Screen6;
lv_obj_t *ui_Label10;
void ui_event_Keyboard2( lv_event_t * e);
lv_obj_t *ui_Keyboard2;
void ui_event_TextArea2( lv_event_t * e);
lv_obj_t *ui_TextArea2;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t *ui_Screen7;
lv_obj_t *ui_Label12;
void ui_event_Keyboard1( lv_event_t * e);
lv_obj_t *ui_Keyboard1;
void ui_event_TextArea1( lv_event_t * e);
lv_obj_t *ui_TextArea1;


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t *ui_Screen8;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Button9;
lv_obj_t *ui_Label15;
void ui_event_Button10( lv_event_t * e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_Label16;


// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t *ui_Screen9;
void ui_event_ImgButton2( lv_event_t * e);
lv_obj_t *ui_ImgButton2;
void ui_event_Button11( lv_event_t * e);
lv_obj_t *ui_Button11;
lv_obj_t *ui_Label18;
void ui_event_Button12( lv_event_t * e);
lv_obj_t *ui_Button12;
lv_obj_t *ui_Label19;


// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
lv_obj_t *ui_Screen10;
lv_obj_t *ui_Panel11;
void ui_event_Button14( lv_event_t * e);
lv_obj_t *ui_Button14;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Label33;
void ui_event_Button15( lv_event_t * e);
lv_obj_t *ui_Button15;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Switch1;


// SCREEN: ui_Screen11
void ui_Screen11_screen_init(void);
lv_obj_t *ui_Screen11;
void ui_event_Button17( lv_event_t * e);
lv_obj_t *ui_Button17;
lv_obj_t *ui_Label30;
lv_obj_t *ui_TextArea3;
lv_obj_t *ui_Keyboard3;


// SCREEN: ui_Screen12
void ui_Screen12_screen_init(void);
lv_obj_t *ui_Screen12;
void ui_event_ImgButton3( lv_event_t * e);
lv_obj_t *ui_ImgButton3;
lv_obj_t *ui_Label31;


// SCREEN: ui_Screen13
void ui_Screen13_screen_init(void);
lv_obj_t *ui_Screen13;
void ui_event_ImgButton4( lv_event_t * e);
lv_obj_t *ui_ImgButton4;
lv_obj_t *ui_Label29;
void ui_event_Button16( lv_event_t * e);
lv_obj_t *ui_Button16;
lv_obj_t *ui_Label32;


// SCREEN: ui_Screen14
void ui_Screen14_screen_init(void);
lv_obj_t *ui_Screen14;
void ui_event_ImgButton5( lv_event_t * e);
lv_obj_t *ui_ImgButton5;
lv_obj_t *ui_Label35;
void ui_event_Button19( lv_event_t * e);
lv_obj_t *ui_Button19;
lv_obj_t *ui_Label36;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1277979519[1] = {&ui_img_1882376574};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen8_screen_init);
        generateSeed(NULL);
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen7_screen_init);
}
}
void ui_event_Roller2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      getSelectedSeedWord( e );
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      getSelectedSeedWord( e );
}
}
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen9_screen_init);
}
}
void ui_event_Label7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen10, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen10_screen_init);
}
}
void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen9_screen_init);
}
}
void ui_event_Keyboard2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
}
}
void ui_event_TextArea2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea2);
}
}
void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_screen_change( &ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen9_screen_init);
}
}
void ui_event_TextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
}
}
void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
}
}
void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen6_screen_init);
}
}
void ui_event_ImgButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
}
}
void ui_event_Button11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen12, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen12_screen_init);
}
}
void ui_event_Button12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}
void ui_event_Button14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen11, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen11_screen_init);
}
}
void ui_event_Button15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen5_screen_init);
}
}
void ui_event_Button17( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen9_screen_init);
}
}
void ui_event_ImgButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
}
}
void ui_event_ImgButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
}
}
void ui_event_Button16( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen8_screen_init);
      generateSeed( e );
}
}
void ui_event_ImgButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
}
}
void ui_event_Button19( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen9_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen5_screen_init();
ui_Screen6_screen_init();
ui_Screen7_screen_init();
ui_Screen8_screen_init();
ui_Screen9_screen_init();
ui_Screen10_screen_init();
ui_Screen11_screen_init();
ui_Screen12_screen_init();
ui_Screen13_screen_init();
ui_Screen14_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
