// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Button13;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label13;
void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label11;
void ui_event_Label7( lv_event_t * e);
extern lv_obj_t *ui_Label7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label5;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label4;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label6;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Label8;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Label9;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Keyboard2;
void ui_event_TextArea2( lv_event_t * e);
extern lv_obj_t *ui_TextArea2;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t *ui_Screen7;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Keyboard1;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t *ui_Screen8;
void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label15;
void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label16;
// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t *ui_Screen9;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label14;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label17;
void ui_event_Button11( lv_event_t * e);
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label18;
void ui_event_Button12( lv_event_t * e);
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
