// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#include "../../../Flint/Trie.h"
extern TrieNode *myTrie;
extern TrieNode *currentNode;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label3;
void ui_event_Roller2( lv_event_t * e);
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label13;
void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label11;
void ui_event_Label7( lv_event_t * e);
extern lv_obj_t *ui_Label7;

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_Label10;
void ui_event_Keyboard2( lv_event_t * e);
extern lv_obj_t *ui_Keyboard2;
void ui_event_TextArea2( lv_event_t * e);
extern lv_obj_t *ui_TextArea2;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t *ui_Screen7;
extern lv_obj_t *ui_Label12;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t *ui_Screen8;
void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label15;
void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label16;





// SCREEN: ui_Screen112
void ui_Screen112_screen_init(void);
extern lv_obj_t *ui_Screen112;
void ui_event_Button2222( lv_event_t * e);
extern lv_obj_t *ui_Button2222;
void ui_event_ImgButton117( lv_event_t * e);
extern lv_obj_t *ui_ImgButton117;
void ui_event_Button112( lv_event_t * e);
extern lv_obj_t *ui_Button112;
extern lv_obj_t *ui_Label112;
extern lv_obj_t * qr;
// SCREEN: ui_Screen116
void ui_Screen116_screen_init(void);
extern lv_obj_t *ui_Screen116;
void ui_event_Button2225( lv_event_t * e);
extern lv_obj_t *ui_Button2225;
extern lv_obj_t *ui_Label119;
void ui_event_ImgButton114( lv_event_t * e);
extern lv_obj_t *ui_ImgButton114;
// SCREEN: ui_Screen117
void ui_Screen117_screen_init(void);
extern lv_obj_t *ui_Screen117;
void ui_event_Button2228( lv_event_t * e);
extern lv_obj_t *ui_Button2228;
extern lv_obj_t *ui_Label118;
void ui_event_ImgButton118( lv_event_t * e);
extern lv_obj_t *ui_ImgButton118;
// SCREEN: ui_Screen115
void ui_Screen115_screen_init(void);
extern lv_obj_t *ui_Screen115;
extern lv_obj_t *ui_Panel115;
void ui_event_Button116( lv_event_t * e);
extern lv_obj_t *ui_Button116;
extern lv_obj_t *ui_Label1114;
extern lv_obj_t *ui_Label1122;
void ui_event_Button1120( lv_event_t * e);
extern lv_obj_t *ui_Button1120;
void ui_event_ImgButton111( lv_event_t * e);
extern lv_obj_t *ui_ImgButton111;
extern lv_obj_t *ui_Image1112;
// SCREEN: ui_Screen118
void ui_Screen118_screen_init(void);
extern lv_obj_t *ui_Screen118;
void ui_event_Button2226( lv_event_t * e);
extern lv_obj_t *ui_Button2226;
extern lv_obj_t *ui_Label116;
void ui_event_ImgButton119( lv_event_t * e);
extern lv_obj_t *ui_ImgButton119;
extern lv_obj_t * XPub_qr;
// SCREEN: ui_Screen119
void ui_Screen119_screen_init(void);
extern lv_obj_t *ui_Screen119;
void ui_event_ImgButton112( lv_event_t * e);
extern lv_obj_t *ui_ImgButton112;
void ui_event_Button114( lv_event_t * e);
extern lv_obj_t *ui_Button114;
extern lv_obj_t *ui_Label114;
void ui_event_Button1111( lv_event_t * e);
extern lv_obj_t *ui_Button1111;
extern lv_obj_t *ui_Label1118;
extern lv_obj_t *ui_Panel111;
void ui_event_Button1112( lv_event_t * e);
extern lv_obj_t *ui_Button1112;
extern lv_obj_t *ui_Label1119;
void ui_event_Button111( lv_event_t * e);
extern lv_obj_t *ui_Button111;
extern lv_obj_t *ui_Label111;
void ui_event_Button113( lv_event_t * e);
extern lv_obj_t *ui_Button113;
extern lv_obj_t *ui_Label113;
void ui_event_Button115( lv_event_t * e);
extern lv_obj_t *ui_Button115;
extern lv_obj_t *ui_Label115;
// SCREEN: ui_Screen1110
void ui_Screen1110_screen_init(void);
extern lv_obj_t *ui_Screen1110;
void ui_event_ImgButton115( lv_event_t * e);
extern lv_obj_t *ui_ImgButton115;
extern lv_obj_t *ui_Keyboard113;
extern lv_obj_t *ui_TextArea113;
void ui_event_Switch111( lv_event_t * e);
extern lv_obj_t *ui_Switch111;
extern lv_obj_t *ui_Label117;
void ui_event_Button1121( lv_event_t * e);
extern lv_obj_t *ui_Button1121;
// SCREEN: ui_Screen1112
void ui_Screen1112_screen_init(void);
extern lv_obj_t *ui_Screen1112;
extern lv_obj_t *ui_Label1131;
void ui_event_Button2229( lv_event_t * e);
extern lv_obj_t *ui_Button2229;
void ui_event_ImgButton116( lv_event_t * e);
extern lv_obj_t *ui_ImgButton116;
extern lv_obj_t *ui_Label1110;
// SCREEN: ui_Screen1113
void ui_Screen1113_screen_init(void);
extern lv_obj_t *ui_Screen1113;
extern lv_obj_t *ui_Label1129;
void ui_event_Button1116( lv_event_t * e);
extern lv_obj_t *ui_Button1116;
extern lv_obj_t *ui_Label32;
void ui_event_Button2232( lv_event_t * e);
extern lv_obj_t *ui_Button2232;
void ui_event_ImgButton113( lv_event_t * e);
extern lv_obj_t *ui_ImgButton113;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_white_background_resized_25x20_png);   // assets\white_background_resized_25x20.png
LV_IMG_DECLARE( ui_img_black_arrow_resized_25x20_png);   // assets\black_arrow_resized_25x20.png
LV_IMG_DECLARE( ui_img_pure_black_arrow25_png);   // assets\pure_black_arrow25.png
LV_IMG_DECLARE( ui_img_1882376574);   // assets\Screenshot 2023-11-02 054358.png
LV_IMG_DECLARE( ui_img_1404577655);   // assets\three-bars-icon-625.png


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
