// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void getSelectedSeedWord(lv_event_t * e);
void generateSeed(const char* entrypy);
void initiateKeyPair(const char* seedphrase);
void initializeDecoder();
void stopPSBTReceving();
void signAndExport();   
void stopPSBTExporting();
void displayPrivateKey();
void displayAddresses();
void displayPublicKey();
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
