// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen12_screen_init(void)
{
ui_Screen12 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton3 = lv_imgbtn_create(ui_Screen12);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1882376574, NULL);
lv_obj_set_width( ui_ImgButton3, 53);
lv_obj_set_height( ui_ImgButton3, 53);
lv_obj_set_x( ui_ImgButton3, 189 );
lv_obj_set_y( ui_ImgButton3, -116 );
lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );

ui_Label31 = lv_label_create(ui_Screen12);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -4 );
lv_obj_set_y( ui_Label31, -69 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"Scan Unsigned Transaction ");
lv_obj_add_state( ui_Label31, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
