// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1113_screen_init(void)
{
ui_Screen1113 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1113, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1113, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1113, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1129 = lv_label_create(ui_Screen1113);
lv_obj_set_width( ui_Label1129, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1129, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1129, 10 );
lv_obj_set_y( ui_Label1129, -54 );
lv_obj_set_align( ui_Label1129, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1129,"to\nchange\nbtc\nfee");
lv_obj_add_state( ui_Label1129, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label1129, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1129, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1129, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1116 = lv_btn_create(ui_Screen1113);
lv_obj_set_height( ui_Button1116, 65);
lv_obj_set_width( ui_Button1116, lv_pct(81));
lv_obj_set_x( ui_Button1116, 1 );
lv_obj_set_y( ui_Button1116, 98 );
lv_obj_set_align( ui_Button1116, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1116, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1116, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1116, lv_color_hex(0xFF7129), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1116, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button1116, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button1116, lv_color_hex(0x702828), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1116, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button1116, lv_color_hex(0x6D0E0E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button1116, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button1116, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button1116, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label32 = lv_label_create(ui_Button1116);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, 0 );
lv_obj_set_y( ui_Label32, -1 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"Sign and export");
lv_obj_add_state( ui_Label32, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2232 = lv_btn_create(ui_Screen1113);
lv_obj_set_width( ui_Button2232, 52);
lv_obj_set_height( ui_Button2232, 47);
lv_obj_set_x( ui_Button2232, -210 );
lv_obj_set_y( ui_Button2232, -130 );
lv_obj_set_align( ui_Button2232, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2232, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2232, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2232, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2232, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button2232, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button2232, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton113 = lv_imgbtn_create(ui_Screen1113);
lv_imgbtn_set_src(ui_ImgButton113, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_white_background_resized_25x20_png, NULL);
lv_obj_set_height( ui_ImgButton113, 26);
lv_obj_set_width( ui_ImgButton113, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton113, lv_pct(-45) );
lv_obj_set_y( ui_ImgButton113, lv_pct(-40) );
lv_obj_set_align( ui_ImgButton113, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button1116, ui_event_Button1116, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2232, ui_event_Button2232, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton113, ui_event_ImgButton113, LV_EVENT_ALL, NULL);

}
