// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen119_screen_init(void)
{
ui_Screen119 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen119, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen119, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen119, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton112 = lv_imgbtn_create(ui_Screen119);
lv_imgbtn_set_src(ui_ImgButton112, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1882376574, NULL);
lv_obj_set_width( ui_ImgButton112, 53);
lv_obj_set_height( ui_ImgButton112, 53);
lv_obj_set_x( ui_ImgButton112, 189 );
lv_obj_set_y( ui_ImgButton112, -116 );
lv_obj_set_align( ui_ImgButton112, LV_ALIGN_CENTER );

ui_Button114 = lv_btn_create(ui_Screen119);
lv_obj_set_width( ui_Button114, lv_pct(12));
lv_obj_set_height( ui_Button114, lv_pct(14));
lv_obj_set_x( ui_Button114, lv_pct(-42) );
lv_obj_set_y( ui_Button114, lv_pct(-42) );
lv_obj_set_align( ui_Button114, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button114, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button114, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button114, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button114, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button114, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button114, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button114, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button114, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button114, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button114, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button114, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button114, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button114, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label114 = lv_label_create(ui_Button114);
lv_obj_set_width( ui_Label114, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label114, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label114, 0 );
lv_obj_set_y( ui_Label114, -1 );
lv_obj_set_align( ui_Label114, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label114,"=");
lv_obj_add_state( ui_Label114, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label114, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label114, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label114, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1111 = lv_btn_create(ui_Screen119);
lv_obj_set_width( ui_Button1111, lv_pct(80));
lv_obj_set_height( ui_Button1111, lv_pct(20));
lv_obj_set_x( ui_Button1111, lv_pct(0) );
lv_obj_set_y( ui_Button1111, lv_pct(-2) );
lv_obj_set_align( ui_Button1111, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1111, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1111, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1111, lv_color_hex(0xAD9999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button1111, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button1111, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1111, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button1111, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button1111, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button1111, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button1111, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1118 = lv_label_create(ui_Button1111);
lv_obj_set_width( ui_Label1118, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1118, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1118, -2 );
lv_obj_set_y( ui_Label1118, 0 );
lv_obj_set_align( ui_Label1118, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1118,"Sign a trancation");
lv_obj_add_state( ui_Label1118, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label1118, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1118, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1118, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel111 = lv_obj_create(ui_Screen119);
lv_obj_set_width( ui_Panel111, 224);
lv_obj_set_height( ui_Panel111, 317);
lv_obj_set_x( ui_Panel111, -359 );
lv_obj_set_y( ui_Panel111, -6 );
lv_obj_set_align( ui_Panel111, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel111, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel111, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1112 = lv_btn_create(ui_Panel111);
lv_obj_set_width( ui_Button1112, lv_pct(119));
lv_obj_set_height( ui_Button1112, lv_pct(20));
lv_obj_set_x( ui_Button1112, lv_pct(-1) );
lv_obj_set_y( ui_Button1112, lv_pct(-9) );
lv_obj_set_align( ui_Button1112, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1112, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1112, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1112, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1112, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Button1112, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Button1112, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Button1112, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Button1112, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button1112, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button1112, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button1112, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button1112, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1112, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button1112, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button1112, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button1112, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button1112, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1119 = lv_label_create(ui_Button1112);
lv_obj_set_width( ui_Label1119, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1119, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1119, 0 );
lv_obj_set_y( ui_Label1119, -1 );
lv_obj_set_align( ui_Label1119, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1119,"Addresses");
lv_obj_add_state( ui_Label1119, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label1119, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1119, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1119, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button111 = lv_btn_create(ui_Panel111);
lv_obj_set_width( ui_Button111, lv_pct(119));
lv_obj_set_height( ui_Button111, lv_pct(20));
lv_obj_set_x( ui_Button111, lv_pct(-1) );
lv_obj_set_y( ui_Button111, lv_pct(11) );
lv_obj_set_align( ui_Button111, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button111, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button111, LV_OBJ_FLAG_SCROLLABLE );    /// Flags   CF1D1D
lv_obj_set_style_bg_color(ui_Button111, lv_color_hex(0xD6482C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button111, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button111, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button111, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button111, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button111, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button111, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button111, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button111, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button111, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button111, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label111 = lv_label_create(ui_Button111);
lv_obj_set_width( ui_Label111, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label111, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label111, 0 );
lv_obj_set_y( ui_Label111, -1 );
lv_obj_set_align( ui_Label111, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label111,"Private Key");
lv_obj_add_state( ui_Label111, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label111, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label111, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label111, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button113 = lv_btn_create(ui_Panel111);
lv_obj_set_width( ui_Button113, lv_pct(119));
lv_obj_set_height( ui_Button113, lv_pct(20));
lv_obj_set_x( ui_Button113, lv_pct(-1) );
lv_obj_set_y( ui_Button113, lv_pct(-29) );
lv_obj_set_align( ui_Button113, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button113, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button113, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button113, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button113, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Button113, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Button113, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Button113, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Button113, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button113, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button113, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button113, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button113, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button113, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button113, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button113, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button113, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button113, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label113 = lv_label_create(ui_Button113);
lv_obj_set_width( ui_Label113, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label113, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label113, 0 );
lv_obj_set_y( ui_Label113, -1 );
lv_obj_set_align( ui_Label113, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label113,"Public Key");
lv_obj_add_state( ui_Label113, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label113, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label113, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label113, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button115 = lv_btn_create(ui_Panel111);
lv_obj_set_width( ui_Button115, lv_pct(33));
lv_obj_set_height( ui_Button115, lv_pct(16));
lv_obj_set_x( ui_Button115, lv_pct(-41) );
lv_obj_set_y( ui_Button115, lv_pct(-48) );
lv_obj_set_align( ui_Button115, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button115, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button115, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button115, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button115, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button115, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button115, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Button115, 45, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Button115, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button115, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_color(ui_Button115, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_main_stop(ui_Button115, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_stop(ui_Button115, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_grad_dir(ui_Button115, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label115 = lv_label_create(ui_Button115);
lv_obj_set_width( ui_Label115, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label115, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label115, 0 );
lv_obj_set_y( ui_Label115, -1 );
lv_obj_set_align( ui_Label115, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label115,"=");
lv_obj_add_state( ui_Label115, LV_STATE_PRESSED );     /// States
lv_obj_set_style_text_color(ui_Label115, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label115, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label115, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton112, ui_event_ImgButton112, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button114, ui_event_Button114, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1111, ui_event_Button1111, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1112, ui_event_Button1112, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button111, ui_event_Button111, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button113, ui_event_Button113, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button115, ui_event_Button115, LV_EVENT_ALL, NULL);

}
