// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1110_screen_init(void)
{
ui_Screen1110 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1110, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1110, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1110, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton115 = lv_imgbtn_create(ui_Screen1110);
lv_imgbtn_set_src(ui_ImgButton115, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_black_arrow_resized_25x20_png, NULL);
lv_obj_set_height( ui_ImgButton115, 33);
lv_obj_set_width( ui_ImgButton115, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton115, lv_pct(-45) );
lv_obj_set_y( ui_ImgButton115, lv_pct(-40) );
lv_obj_set_align( ui_ImgButton115, LV_ALIGN_CENTER );

ui_Keyboard113 = lv_keyboard_create(ui_Screen1110);
lv_obj_set_width( ui_Keyboard113, 475);
lv_obj_set_height( ui_Keyboard113, 214);
lv_obj_set_x( ui_Keyboard113, -4 );
lv_obj_set_y( ui_Keyboard113, 48 );
lv_obj_set_align( ui_Keyboard113, LV_ALIGN_CENTER );

ui_TextArea113 = lv_textarea_create(ui_Screen1110);
lv_obj_set_width( ui_TextArea113, 451);
lv_obj_set_height( ui_TextArea113, LV_SIZE_CONTENT);   /// 112
lv_obj_set_x( ui_TextArea113, -2 );
lv_obj_set_y( ui_TextArea113, -86 );
lv_obj_set_align( ui_TextArea113, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea113,"max 100 characters");



ui_Switch111 = lv_switch_create(ui_Screen1110);
lv_obj_set_width( ui_Switch111, 50);
lv_obj_set_height( ui_Switch111, 25);
lv_obj_set_x( ui_Switch111, 198 );
lv_obj_set_y( ui_Switch111, -127 );
lv_obj_set_align( ui_Switch111, LV_ALIGN_CENTER );


ui_Label117 = lv_label_create(ui_Screen1110);
lv_obj_set_width( ui_Label117, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label117, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label117, -27 );
lv_obj_set_y( ui_Label117, -133 );
lv_obj_set_align( ui_Label117, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label117,"BIP-39 passphrase");
lv_obj_set_style_text_font(ui_Label117, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton115, ui_event_ImgButton115, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard113,ui_TextArea113);
lv_obj_add_event_cb(ui_Switch111, ui_event_Switch111, LV_EVENT_ALL, NULL);

}
