// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../../lvgl/src/widgets/keyboard/lv_keyboard_binary.h"
#include "../../../lvgl/src/widgets/keyboard/lv_keyboard_seed.h"
void ui_Screen11_screen_init(void)
{



 static const char * kb_map[] = {"0000", "0001", "0010", "0011", "0100", "0101", "0110", "0111", "1000", "1001", LV_SYMBOL_BACKSPACE, "\n",
                                    "1010", "1011", "1100", "1101", "1110", "1111", LV_SYMBOL_DRIVE, LV_SYMBOL_VOLUME_MAX, LV_SYMBOL_EJECT,  LV_SYMBOL_NEW_LINE, "\n",
                                    LV_SYMBOL_SAVE, LV_SYMBOL_BARS, LV_SYMBOL_CALL, LV_SYMBOL_DIRECTORY, LV_SYMBOL_WARNING, LV_SYMBOL_EYE_CLOSE, LV_SYMBOL_EYE_OPEN, LV_SYMBOL_LIST, ":", "!", "?", "\n",
                                    LV_SYMBOL_CLOSE, LV_SYMBOL_HOME,  LV_SYMBOL_SETTINGS, LV_SYMBOL_POWER, LV_SYMBOL_OK, NULL
                                   };
                                       static const lv_btnmatrix_ctrl_t kb_ctrl[] = {4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6,
                                                     4, 4, 4, 4, 4, 4, 4, 4, 4, 6,
                                                     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                                                     2, 2| 2, 6, 2 | 2, 2
                                                    };


ui_Screen11 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen11, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button17 = lv_btn_create(ui_Screen11);
lv_obj_set_width( ui_Button17, 68);
lv_obj_set_height( ui_Button17, 38);
lv_obj_set_x( ui_Button17, -190 );
lv_obj_set_y( ui_Button17, -133 );
lv_obj_set_align( ui_Button17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Button17);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, -15 );
lv_obj_set_y( ui_Label30, -1 );
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"<");
lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Screen11);
lv_obj_set_width( ui_TextArea3, 420);
lv_obj_set_height( ui_TextArea3, LV_SIZE_CONTENT);   /// 112
lv_obj_set_x( ui_TextArea3, 1 );
lv_obj_set_y( ui_TextArea3, -85 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea3,"Placeholder...");



//ui_Keyboard3 = lv_keyboard_create(ui_Screen11);
ui_Keyboard3 = lv_ex_btnmatrix_binary(ui_Screen11);


lv_keyboard_set_popovers(ui_Keyboard3,true);
// lv_keyboard_set_map(ui_Keyboard3, LV_KEYBOARD_MODE_USER_1, kb_map, kb_ctrl);


lv_obj_set_width( ui_Keyboard3, 475);
lv_obj_set_height( ui_Keyboard3, 214);
lv_obj_set_x( ui_Keyboard3, -4 );
lv_obj_set_y( ui_Keyboard3, 48 );
lv_obj_set_align( ui_Keyboard3, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard3,ui_TextArea3);

}
