// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen115_screen_init(void)
{
ui_Screen115 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen115, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen115, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen115, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel115 = lv_obj_create(ui_Screen115);
lv_obj_set_width( ui_Panel115, 607);
lv_obj_set_height( ui_Panel115, 50);
lv_obj_set_x( ui_Panel115, 4 );
lv_obj_set_y( ui_Panel115, -79 );
lv_obj_set_align( ui_Panel115, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel115, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button116 = lv_btn_create(ui_Panel115);
lv_obj_set_width( ui_Button116, 100);
lv_obj_set_height( ui_Button116, 37);
lv_obj_set_x( ui_Button116, 206 );
lv_obj_set_y( ui_Button116, -1 );
lv_obj_set_align( ui_Button116, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button116, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button116, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button116, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button116, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button116, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button116, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1114 = lv_label_create(ui_Button116);
lv_obj_set_width( ui_Label1114, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1114, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1114, -15 );
lv_obj_set_y( ui_Label1114, 0 );
lv_obj_set_align( ui_Label1114, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1114,"ON");
lv_obj_set_style_text_color(ui_Label1114, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1114, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1114, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1122 = lv_label_create(ui_Screen115);
lv_obj_set_width( ui_Label1122, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1122, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1122, -146 );
lv_obj_set_y( ui_Label1122, -79 );
lv_obj_set_align( ui_Label1122, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1122,"BIP-39 passphrase");

ui_Button1120 = lv_btn_create(ui_Screen115);
lv_obj_set_width( ui_Button1120, 50);
lv_obj_set_height( ui_Button1120, 47);
lv_obj_set_x( ui_Button1120, -213 );
lv_obj_set_y( ui_Button1120, -133 );
lv_obj_set_align( ui_Button1120, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1120, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1120, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1120, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1120, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button1120, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button1120, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton111 = lv_imgbtn_create(ui_Screen115);
lv_imgbtn_set_src(ui_ImgButton111, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_black_arrow_resized_25x20_png, NULL);
lv_obj_set_height( ui_ImgButton111, 33);
lv_obj_set_width( ui_ImgButton111, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton111, lv_pct(-45) );
lv_obj_set_y( ui_ImgButton111, lv_pct(-40) );
lv_obj_set_align( ui_ImgButton111, LV_ALIGN_CENTER );

ui_Image1112 = lv_img_create(ui_Screen115);
lv_img_set_src(ui_Image1112, &ui_img_pure_black_arrow25_png);
lv_obj_set_width( ui_Image1112, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Image1112, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_Image1112, 226 );
lv_obj_set_y( ui_Image1112, -81 );
lv_obj_set_align( ui_Image1112, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1112, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1112, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Button116, ui_event_Button116, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1120, ui_event_Button1120, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton111, ui_event_ImgButton111, LV_EVENT_ALL, NULL);

}
