// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen11_screen_init(void)
{
ui_Screen11 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen11, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button17 = lv_btn_create(ui_Screen11);
lv_obj_set_width( ui_Button17, 68);
lv_obj_set_height( ui_Button17, 38);
lv_obj_set_x( ui_Button17, -190 );
lv_obj_set_y( ui_Button17, -133 );
lv_obj_set_align( ui_Button17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Button17);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, -15 );
lv_obj_set_y( ui_Label30, -1 );
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"<");
lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Screen11);
lv_obj_set_width( ui_TextArea3, 420);
lv_obj_set_height( ui_TextArea3, LV_SIZE_CONTENT);   /// 112
lv_obj_set_x( ui_TextArea3, -2 );
lv_obj_set_y( ui_TextArea3, -40 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea3,"Placeholder...");



ui_Keyboard3 = lv_keyboard_create(ui_Screen11);
lv_obj_set_width( ui_Keyboard3, 300);
lv_obj_set_height( ui_Keyboard3, 120);
lv_obj_set_x( ui_Keyboard3, -31 );
lv_obj_set_y( ui_Keyboard3, 92 );
lv_obj_set_align( ui_Keyboard3, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard3,ui_TextArea3);

}
